services:
  app:
    image: app
    environment:
      - DB_HOST=db
      - DB_PASSWORD=root
    depends_on:
      - db
    ports:
      - 5000:5000
    links:
      - db
    build: sudoku
  
  db:
    image: db
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=sudoku
    build: db
    
  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
    build: nginx
    links:
      - app
    depends_on:
      app:
        condition: service_started
        restart: true