services:
  app:
    image: sudoku_app
    environment:
      - DB_HOST=db
      - DB_PASSWORD=root
    depends_on:
      - db
    ports:
      - 5000:5000
    links:
      - db
    build: sudoku
  
  db:
    image: sudoku_db
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=sudoku
    build: db